# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# general
set -g default-terminal "screen-256color" # colors!
set -s escape-time 10                     # faster command sequences
set -sg repeat-time 600                   # increase repeat timeout
set -s focus-events on


# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-t
bind-key C-t send-prefix

# split panes in a better way
bind o split-window -h
bind u split-window -v
unbind '"'
unbind %

# vim movement
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none