#!/usr/bin/env bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all

Mod=Mod4
Alt=Mod1
Terminal=alacritty
FileManager=pcmanfm
Editor=emacs
Web="chromium -no-default-browser-check"

xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal 
hc set_monitors 1920x1080+0+0
hc pad 0 30

# xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP-4 --mode 1920x1080 --pos 0x0 --rotate normal 
# hc set_monitors 1920x1080+0+0 1920x1080+1920+0
# hc pad 0 30
# hc pad 1 30

xsetroot -solid '#000000'
xsetroot -cursor_name left_ptr &

~/.config/polybar/launch.sh

nm-applet &
pamac-tray &
numlockx on &
blueberry-tray &
run volumeicon &

pkill -u $USER '^picom$'

# use the picom.conf in .config folder
picom  --experimental-backend

nitrogen --restore &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xfce4-power-manager &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
/usr/bin/emacs --daemon &

hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         use_index +1 --skip-visible
hc keybind $Mod-Shift-Tab   use_index -1 --skip-visible
hc keybind $Mod-period         use_index +1 --skip-visible
hc keybind $Mod-comma       use_index -1 --skip-visible
hc keybind $Mod-i           jumpto urgent

hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

hc keybind $Alt-Shift-h chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Alt-Shift-j chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Alt-Shift-k chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
hc keybind $Alt-Shift-l chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

hc keybind $Alt-Shift-Left chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Alt-Shift-Down chain , lock , shift_to_monitor -l , focus_monitor -l , unlock
hc keybind $Alt-Shift-Up chain , lock , shift_to_monitor -r , focus_monitor -r , unlock
hc keybind $Alt-Shift-Right chain , lock , shift_to_monitor -r , focus_monitor -r , unlock

hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-Control-space split explode
hc keybind $Mod-r remove

resizestep=0.05

hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc unrule -F
hc rule focus=on # normally focus new clients
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule class=VirtualBox fullscreen=on

#tag_names=( {1..10} )
tag_names=("I" "II" "III" "IV" "V" "VI" "VII" "VIII" "IX" "X")

tag_keys=( "1" "2" "3" "4" "5" "6" "7" "8" "9" "0" )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    # horizontal tiling as standard
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" chain , move_index "$i" , use_index "$i"
    fi
done

hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-space                                                \
          or , and . compare tags.focus.curframe_wcount = 2          \
                   . cycle_layout +1 vertical horizontal max grid    \
             , cycle_layout +1

hc attr theme.active.color '#6790EB'
hc attr theme.active.inner_color '#141414'
hc attr theme.active.outer_color '#6790EB'
hc attr theme.background_color '#141414'
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.inner_color black
hc attr theme.inner_width 1
hc attr theme.normal.color '#141414'
hc attr theme.urgent.color orange

hc set always_show_frame 1
hc set focus_follows_mouse 1
hc set frame_border_active_color '#6790EB'
hc set frame_border_normal_color '#141414'
hc set frame_bg_normal_color '#141414'
hc set frame_bg_active_color '#000000'
hc set frame_border_width 3
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 5
hc set frame_padding 0
hc set mouse_recenter_gap 0
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 0
hc set tree_style '╾│ ├└╼─┐'
hc set window_gap 5

hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-Shift-q      close
hc keybind $Mod-Return       spawn $Terminal
hc keybind $Mod-Shift-Return spawn $FileManager
hc keybind $Mod-Shift-r      reload
hc keybind $Mod-x            spawn arcolinux-logout
hc keybind $Mod-v            spawn pavucontrol
hc keybind $Mod-Escape       spawn xkill
hc keybind $Mod-d            spawn dmenu_run
hc keybind $Mod-Shift-d      spawn rofi -show run

hc keybind $Mod-t       spawn telegram-desktop
hc keybind $Mod-Shift-t spawn teams
hc keybind $Mod-w       spawn $Web
hc keybind $Mod-e       spawn $Editor

hc unlock
