#+TITLE: My XMonad config (work in progress)
#+AUTHOR: Antonio Petrillo

* Import
These are all the library that I need for my XMonad configuration.
#+begin_src haskell :tangle xmonad.hs
import XMonad
import System.IO
import System.Exit

import qualified XMonad.StackSet as W
import qualified Data.Map        as M

import XMonad.Util.SpawnOnce
import XMonad.Util.Run
import XMonad.Util.EZConfig

import XMonad.Hooks.ManageDocks (avoidStruts)
import XMonad.Hooks.DynamicLog
import XMonad.Hooks.ManageDocks
import XMonad.Hooks.EwmhDesktops

import XMonad.Actions.MouseResize

import XMonad.Layout.Spacing
import XMonad.Layout.Tabbed 
import XMonad.Layout.NoBorders
import XMonad.Layout.Renamed
import XMonad.Layout.Spiral
import XMonad.Layout.MultiToggle
import XMonad.Layout.MultiToggle.Instances

import Data.Maybe (isJust, fromJust)
#+end_src
* My default program
I have defined a variable for all my favorite application for two reason:
  1. I can use the variable name in the config (*I can also set some parameter for terminal app*)
  2. I can easily change if I discover a better substitute
#+begin_src haskell :tangle xmonad.hs
myTerminal         = "alacritty"
myFallbackTerminal = "cool-retro-term"
fallbackTerminal   = "konsole"
myLauncher         = "dmenu_run"
myFileManager      = "pcmanfm"
myBrowser          = "google-chrome-stable"
myEditor           = "emacs" -- maybe someday I can change it to vim, but I don't think so
emacs              = "emacs"
emacsExec          = emacs ++ " --eval "
#+end_src
* My window manager parameter
Parameter to use all along the config.
#+begin_src haskell :tangle xmonad.hs
myBorderWidth   = 2
myGaps          = 2

myFocusFollowsMouse :: Bool
myFocusFollowsMouse = True

myModMask       = mod4Mask

myWorkspaces    = map show [1..9]
myWorkspaceIndices = M.fromList $ zipWith (,) myWorkspaces [1..]

myNormalBorderColor  = "#474646"
myFocusedBorderColor = "#83a598"

myFont = "xft:Fira Code:style=Retina,Regular"
#+end_src
* My keybinding
The most important section, I used the /classic scheme/ for the workspace workflow, and EZ way for all the others.
I didn't know how to set the bindings for the workspace handling in the EZ way...
I prefer the EZ way, even if it's harder to find error in it, because is more readable and more easy to write and remember the Emacs keybinding.
#+begin_src haskell :tangle xmonad.hs
myKeys conf@(XConfig {XMonad.modMask = modKey}) = M.fromList $
    [((m .|. modKey, k), windows $ f i)
        | (i, k) <- zip (XMonad.workspaces conf) [xK_1 .. xK_9]
        , (f, m) <- [(W.greedyView, 0), (W.shift, shiftMask)]]

myAdditionalKeys = [ -- Basic keybindings
                     ("M-<Return>"  , spawn $ myTerminal) 
                   , ("M1-C-t"      , spawn $ myFallbackTerminal)
                   , ("M-d"         , spawn myLauncher)
                   , ("M-w"         , spawn myBrowser)
                   , ("M-e"         , spawn myEditor)
                   , ("M-S-<Return>", spawn myFileManager)
                   , ("M-S-q"       , kill)
                   , ("M-<Space>"   , sendMessage NextLayout)
                   , ("M-n"         , refresh)
                   , ("M-<Tab>"     , windows W.focusDown)
                   , ("M-S-<Tab>"   , windows W.focusUp)
                   , ("M-j"         , windows W.focusDown)
                   , ("M-k"         , windows W.focusUp)
                   , ("M-m"         , windows W.focusMaster)
                   , ("M-C-<Return>", windows W.swapMaster)
                   , ("M-S-j"       , windows W.swapDown)
                   , ("M-S-k"       , windows W.swapUp)
                   , ("M-h"         , sendMessage Shrink)
                   , ("M-l"         , sendMessage Expand)
                   , ("M-t"         , withFocused $ windows . W.sink)
                   , ("M-,"         , sendMessage (IncMasterN 1))
                   , ("M-."         , sendMessage (IncMasterN (-1)))
                   , ("M-f"         , sendMessage $ Toggle FULL)
                   -- , ("M-S-x"       , io (exitWith ExitSuccess))
                   , ("M-S-x"       , spawn $ "arcolinux-logout")
                   , ("M-x"         , spawn $ "xmonad --recompile && xmonad --restart")
                   , ("M-<Esc>"     , spawn $ "xkill")

                   -- Emacs integration
                   , ("C-e C-j"     , spawn (emacsExec ++ "'(dired nil)'" ))
                   , ("C-e C-x"     , spawn (emacsExec ++ "'(dired \"~/.xmonad\")'"))  -- open xmonad folder
                   , ("C-e C-e"     , spawn (emacsExec ++ "'(dired \"~/.emacs.d\")'")) -- open emacs folder
                   , ("C-e C-a"     , spawn (emacsExec ++ "'(dired \"~/.config/awesome\")'")) -- open emacs folder
                   , ("C-e C-c"     , spawn (emacsExec ++ "'(dired \"~/.config\")'"))  -- open config folder
                   , ("C-e e"       , spawn (emacsExec ++ "'(eshell)'"))
                   , ("C-e t"       , spawn (emacsExec ++ "'(vterm)'"))
                   , ("C-e d"       , spawn (emacsExec ++ "'(dashboard-refresh-buffer)'"))

                   -- Keybinds to launch app
                   , ("M-a h"       , spawn (myTerminal ++ " -e htop"))
                   , ("M-a f"       , spawn (myTerminal ++ " -e ranger"))
                   , ("M-a u"       , spawn (myTerminal ++ " -e sudo pacman -Syyu"))
                   , ("M-a e"       , spawn (myTerminal ++ " -e nvim"))
                   , ("M-a t"       , spawn ("telegram-desktop"))
                   , ("M-a S-t"     , spawn ("teams"))

                   -- toggle between dark/light mode 
                   , ("M-s S-d"     , spawn ("feh --bg-scale ~/Pictures/wallpaper/gruvbox_dark_arch.png"))
                   , ("M-s S-l"     , spawn ("feh --bg-scale ~/Pictures/wallpaper/gruvbox_light_arch.png"))
                   ]

myMouseBindings (XConfig {XMonad.modMask = modMask}) = M.fromList $
    [ ((modMask, button1), (\w -> focus w >> mouseMoveWindow w))
    , ((modMask, button2), (\w -> focus w >> windows W.swapMaster))
    , ((modMask, button3), (\w -> focus w >> mouseResizeWindow w))
    ]
#+end_src
* My Layout
The second most important section, all the possible layout are:
+ Master & Stack, with Master on the left
+ Master & Stack, with Master on top
+ Spiral, like bspwm, I call it Fibonacci Layout
+ Tabbed, like one of the default layout in I3
+ FullScreen, I don't realy use it, but sometime it can be useful [fn:1]
#+begin_src haskell :tangle xmonad.hs
myLayout = avoidStruts $ mkToggle (NOBORDERS ?? FULL ?? EOT) $ mouseResize  myDefaultLayout
  where
    myDefaultLayout = myTiledLayout
                      ||| Mirror myTiledLayout
                      ||| fibonacci
                      ||| myTabbedLayout
                      ||| noBorders Full 

myTiledLayout = spacing myGaps (Tall nmaster delta ratio)
  where
    nmaster = 1
    ratio   = 1/2
    delta   = 2/100

fibonacci = spacing myGaps $ smartBorders $ spiral (6/7)

myManageHook = composeAll
    [ className =? "MPlayer"          --> doFloat
    , className =? "Gimp"             --> doFloat
    , resource  =? "desktop_window"   --> doIgnore ]

myTabbedLayout = tabbed shrinkText myTabTheme

myTabTheme = def { fontName            = myFont
                 , activeColor         = "#83a598"
                 , inactiveColor       = "#474646"
                 , activeBorderColor   = "#83a598"
                 , inactiveBorderColor = "#474646"
                 , activeTextColor     = "#474646"
                 , inactiveTextColor   = "#83a598"
                 }

#+end_src
[fn:1] I can toggle to ~Full~ layout with ~M-f~
* My hook
Just the autostart section, I have to learn a little bit more about LogHook
#+begin_src haskell :tangle xmonad.hs
myLogHook = return ()

myStartupHook = do
    spawnOnce "picom --experimental-backend &"
    spawnOnce "feh --bg-scale ~/Pictures/wallpaper/gruvbox_dark_arch.png &"
    spawnOnce "lxsession &"
    spawnOnce "udiskie &"
    spawnOnce "xmobar ~/.xmonad/xmobarrc"
    spawnOnce "xsetroot -cursor_name left_ptr &"
    spawnOnce "xsetroot -solid '#e69933'"
#+end_src
* My config
Applying all the definition above
#+begin_src haskell :tangle xmonad.hs
myConfig = defaultConfig {
        terminal           = myTerminal,
        focusFollowsMouse  = myFocusFollowsMouse,
        borderWidth        = myBorderWidth,
        modMask            = myModMask,
        workspaces         = myWorkspaces,
        normalBorderColor  = myNormalBorderColor,
        focusedBorderColor = myFocusedBorderColor,

        keys               = myKeys,
        mouseBindings      = myMouseBindings,

        layoutHook         = myLayout,
        manageHook         = myManageHook <+> manageDocks,
        logHook            = myLogHook,
        startupHook        = myStartupHook
    }
#+end_src
* Utility
Adding clickable workspace in XMobar
#+begin_src haskell :tangle xmonad.hs
clickable ws = "<action=xdotool key super+"++show i++">"++ws++"</action>"
    where i = fromJust $ M.lookup ws myWorkspaceIndices

windowCount :: X (Maybe String)
windowCount = gets $ Just . show . length . W.integrate' . W.stack . W.workspace . W.current . windowset
#+end_src
* Main function
Starting point of XMonad and XMobar integration
#+begin_src haskell :tangle xmonad.hs
main = do
  xmproc <- spawnPipe "xmobar  ~/.xmonad/xmobarrc"
  xmonad $ ewmh myConfig
    { handleEventHook = docksEventHook
    , logHook         = dynamicLogWithPP $ xmobarPP
                           { ppOutput          = \x -> hPutStrLn xmproc x
                           , ppCurrent         = xmobarColor "#e69933" "" . wrap "[" "]"
                           , ppVisible         = xmobarColor "#e69933" "" . clickable
                           , ppHidden          = xmobarColor "#b17711" "" . wrap "*" "" . clickable
                           , ppHiddenNoWindows = xmobarColor "#b69933" "" . clickable
                           , ppTitle           = xmobarColor "#CCCCCC" "" . shorten 60
                           , ppSep             = "<fc=#e69933> <fn=2>|</fn> </fc>"
                           , ppUrgent          = xmobarColor "#C45500" "" . wrap "!" "!" 
                           , ppExtras          = [windowCount]
                           , ppOrder           = \(ws:l:t:ex) -> [ws,l] ++ ex ++ [t]
                           }
    } `additionalKeysP` myAdditionalKeys
#+end_src
* XMobar
Config for XMobar, at a first glance it seems complicated, but after a little bit I found easy to configure XMobar than polybar
#+begin_src haskell :tangle xmobarrc
Config { font = "xft:Fira Code Retina:pixelsize=12:antialias=true:hinting=true"
       , additionalFonts = [ "xft:FontAwesome:pixelsize=9"
                           , "xft:Mononoki Nerd Font:pixelsize=12:antialias=true:hinting=true"]
       , borderColor = "black"
       , border = TopB
       , bgColor = "#282828"
       , fgColor = "#ebdbb2"
       , alpha = 255
       , position = Top
       , textOffset = -1
       , iconOffset = -1
       , lowerOnStart = True
       , pickBroadest = False
       , persistent = True
       , hideOnStart = False
       , iconRoot = "/home/anto/.xmonad/xpm/" 
       , allDesktops = True
       , overrideRedirect = True
       , commands = [ Run Network "wlp4s0" ["-t", "<fc=#83a598><fn=2>\xf0aa </fn></fc> <rx>kb  <fc=#83a598><fn=2>\xf0ab </fn></fc> <rx>kb"] 30
                    , Run Cpu ["-t", "<fc=#83a598><fn=2>\xf108 </fn></fc> cpu:<total>%", "-H", "50", "--high", "red"] 20
                    , Run Memory ["-t","<fc=#83a598><fn=2>\xf233 </fn></fc> mem: <used> MB"] 20
                    , Run Com "uname" ["-s", "-r"] "" 36000
                    , Run Date "<fc=#83a598><fn=2>\xf133 </fn></fc> %d %b %Y (%H:%M)" "date" 60
                    , Run UnsafeStdinReader
                    , Run Battery ["-t", "<fc=#83a598><fn=2> </fn></fc><left>% - <timeleft>", "--", "-O", "AC", "-o", "Bat"
                                  ,"-h", "green", "-l", "red"] 10
                    ]
       , sepChar = "%"
       , alignSep = "}{"
       , template = " <icon=haskell_20.xpm/> <fc=#e69933>|</fc> %UnsafeStdinReader% }{ <fc=#83a598><fn=2> </fn></fc><action=`alacritty -e sudo pacman -Syyu`>%uname%</action> <fc=#e69933>|</fc> <action=`alacritty -e htop`>%cpu%</action> <fc=#e69933>|</fc> <action=`alacritty -e htop`>%memory%</action> <fc=#e69933>|</fc> <action=`alacritty -e nmtui`>%wlp4s0%</action> <fc=#e69933>|</fc> %battery% <fc=#e69933>|</fc> %date%"
       }
#+end_src
* TODO 
+ [ ] Add more documetation to the configuration
+ [1/2] Obviously extend this configuration
  + [X] Add a tabbed layout
  + [ ] Add sublayout configuration
+ [6/6] Better support for xmobar
  + [X] Launch xmobar
  + [X] Add mouse action
  + [X] Add Theme
  + [X] Don't let window cover the bar
  + [X] Choice a better colorscheme
  + [X] add more 'stuff'
