source $ZDOTDIR/aliases

autoload -U colors && colors

PROMPT="%F{#ebcb8b}%n%f%F{#bf616a}@%f%F{#ebcb8b}%m%f%F{#a3be8c}%~%f%b "
RPROMPT="%F{#dedee9}%t%f"

setopt autocd
stty stop undef

autoload -Uz compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'l' vi-forward-char
